# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale              : "en-US"
title               : "Dan Zhao"
title_separator     : "-"
name                : "Dan Zhao"
description         : "Postdoc at HU Berlin & PIK"
url                 : "https://zhaodan-npu.github.io" # Correct: Your full URL
baseurl             : "" # Correct: Empty for a user page
repository          : "zhaodan-npu/zhaodan-npu.github.io" # Correct: Your repository name

# Site Author
author:
  # Biographic information
  avatar            : "profile.png"
  name              : "Dan Zhao"
  bio               : "Postdoctoral Researcher in Nonlinear Dynamics"
  location          : "Berlin/P Potsdam, Germany"
  employer          : "Humboldt University of Berlin" # Corrected: Your actual employer
  email             : "zzhaodannn@163.com"

  # Academic websites
  googlescholar     : "https://scholar.google.com/citations?user=maWzg04AAAAJ&hl=en"
  orcid             : "https://orcid.org/0009-0009-1682-6548" # Corrected: Direct link
  scopus            : "https://www.scopus.com/authid/detail.uri?authorId=57485248700"

  # Repositories and software development
  github            : "zhaodan-npu" # Corrected: Your GitHub username

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true


# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
